username: "datasnok"
config: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG') }}"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"

brew_cask_packages:
  - dbeaver-community
  - docker
  - google-chrome
  - iterm2
  - slack
  - spotify
  - visual-studio-code
brew_packages:
  - docker-compose
  - git
  - jq
  - tmux
