---
- name: Install neovim
  become: true
  ansible.builtin.shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-macos-arm64.tar.gz
    rm -rf /opt/nvim
    tar -C /opt -xzf nvim-macos-arm64.tar.gz
    rm nvim-macos-arm64.tar.gz
