---
- name: Download SDKMAN! script
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/install_sdkman.sh

- name: Run SDKMAN!
  command: bash /tmp/install_sdkman.sh
  register: sdkman_result
  failed_when: "'FAILED' in sdkman_result.stderr"
