---
- name: Ensure Zsh with dependencies are installed
  apt:
    name: "{{ ['zsh'] }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
  become: true
