- hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Set fact for macOS
      ansible.builtin.set_fact:
        is_macos: "{{ ansible_facts['os_family'] == 'Darwin' }}"

    - name: Install zsh
      when: not is_macos
      ansible.builtin.include_tasks:
        file: tasks/prereq-zsh.yml

    - name: Install ohmyzsh
      ansible.builtin.include_tasks:
        file: tasks/prereq-ohmyzsh.yml

    - name: Install neovim (Linux)
      when: not is_macos
      ansible.builtin.include_tasks:
        file: tasks/prereq-nvim.yml

    - name: Install neovim (MacOS)
      when: is_macos
      ansible.builtin.include_tasks:
        file: tasks/prereq-nvim-macos.yml

    - name: Install Node Version Manager (nvm)
      ansible.builtin.include_tasks:
        file: tasks/prereq-nvm.yml

    - name: Install SDKMAN!
      ansible.builtin.include_tasks:
        file: tasks/prereq-sdkman.yml

    - name: Install Homebrew packages
      when: is_macos
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present

    - name: Install Homebrew Cask packages
      when: is_macos
      community.general.homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
