- hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Copy home folder
      ansible.builtin.copy:
        src: ../home/
        dest: "{{ home }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
